# Generated by Django 2.1.2 on 2018-11-08 12:53

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_instagramlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12, validators=[validators.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
