# Generated by Django 2.1.2 on 2018-11-08 13:32

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_auto_20181108_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, validators=[validators.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
