# Generated by Django 2.1.2 on 2018-11-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_auto_20181110_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_subcategory_models', to='salon.SubCategory', verbose_name='Подкатегория'),
        ),
    ]
