# Generated by Django 2.1.2 on 2018-11-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_priceitem_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceitem',
            name='for_inline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_price_models', to='salon.PriceItem'),
        ),
    ]
