# Generated by Django 2.1.2 on 2018-11-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_priceitem_for_inline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
