# Generated by Django 2.1.2 on 2018-11-10 01:15

from django.db import migrations, models
import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_auto_20181110_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceitem',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(salon.models.get_del_cat), related_name='category_linked_models', to='salon.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(salon.models.get_del_subcat), related_name='related_subcategory_models', to='salon.SubCategory', verbose_name='Подкатегория'),
        ),
    ]
