# Generated by Django 2.1.2 on 2018-11-10 01:37

from django.db import migrations, models
import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_auto_20181110_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(salon.models.get_del_cat), to='salon.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
