# Generated by Django 2.1.2 on 2018-11-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_auto_20181110_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_linked_models', to='salon.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_subcategory_models', to='salon.SubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Category', verbose_name='Категория'),
        ),
    ]
